version: '3'

services:
  traefik:
    image: traefik:1.6.6-alpine
    container_name: "${NAME}_traefik"
    command: --docker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./.certs:/certs
    networks:
      - proxy
    labels:
      - 'traefik.frontend.rule=Host:monitor.${BASE_DOMAIN}'
      - 'traefik.port=8080'

  portainer:
    depends_on:
      - traefik
    image: portainer/portainer
    container_name: "${NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${BASE_DOMAIN}'

networks:
  proxy:
    external: true
