version: '3'

services:
  traefik:
    image: traefik:1.7.34-alpine
    container_name: traefik
    command: --docker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./.certs:/certs
    networks:
      - proxy
    labels:
      - 'traefik.frontend.rule=Host:monitor.localhost'
      - 'traefik.port=8080'

networks:
  proxy:
    external: true    
